### ISSUE TITLE
Occasional Nginx failure

### ISSUE THREAD

**Issue by peterkingsbury** [kurtcms/docker-compose-wordpress-nginx-mysql#1]
## Problem

Occasionally, after deploying the services listed in `docker-compose.yml`, the Nginx container goes into a crash-loop.

## What I Did

1. Cloned the repository.
2. Created the `.env` file with db/user/password information.
3. Executed the `fetch-certbot-tls` script.
4. Provided my domain and email address when prompted.

## Symptoms

1. Container goes into a tight crash-loop.
5. When inspecting container logs (`docker logs -f nginx`) there is a repeated series of logs indicating the Certbot certificate is inaccessible:
```
nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/$DOMAIN/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/$DOMAIN/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2022/03/17 23:09:13 [emerg] 1#1: cannot load certificate "/etc/letsencrypt/live/$DOMAIN/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/$DOMAIN/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```
## Workarounds

* Re-run everything with `docker-compose down --rmi all && docker system prune -a -f && docker volume prune -f && ./fetch-certbot-tls`

**Comment by kurtcms** [comment]
Thanks for reporting this issue, Peter. From the log that you have shared, it seemed that the reason that NGINX kept crashing and restarting was due to a missing TLS certificate. Generating which is the whole purpose of the `fetch-certbot-tls` script, so I had a closer look at it and it seemed that the missing certificate could be due to: 

1. The `openssl` command failing to generate a dummy certificate for NGINX to start service, and for the script to subsequently obtain a signed certificate with Certbot; or
2. The `certbot` container failing to obtain a signed certificate with Certbot, and with the dummy certificate removed before attempting to obtain a signed certificate, no certificate was then in place and NGINX would as such enter a crash-and-restart loop. 

Logic eliminated the possibility of 1 to a degree, for if it was the case, the `fetch-certbot-tls` script would crash and an error message related to `openssl` would have appeared. Also if it was an issue with `openssl` it would unlikely be intermittent and that stopping all the containers and pruning the system before re-running the script would unlikely fix it. But if it was 2, there also would have been an error message related to the `certbot` container that would shed light on the culprit. 

This prompted for a test with an eye on 2. I did it with a new domain on a new virtual machine and I confirmed that I could reproduce the intermittent issue. The `openssl` command was able to generate a dummy certificate without any error which eliminated 1. The `certbot` container did at times output error message on failing to obtain a signed certificate, which suggested 2.  The intermittence of the issue pointed however to the codes between generating a dummy certificate and requesting a signed certificate, for the `certbot` container was for sure more tried and trusted. After some digging, it seemed that the culprit was with `sleep 3`. 

The reason for a `sleep 3` was to give NGINX an appropriate amount of time to recognise that the dummy certificate was now in place and to start service, for it being in service to answer the HTTP-01 challenge by Let’s Encrypt was required to obtain a signed certificate. 3 seconds were usually adequate for NGINX to do this. But at times they weren't. As such, to fix this, I will replace the `sleep 3` with a `docker-compose restart nginx`. This would ensure that NGINX has all the time it needs to restart with the dummy certificate before moving on to the next step. 

Thanks again for reporting this, Peter. And apologies for the late response. Major changes in life lately. Quitted my previous job and starting life in a completely new country. A lot were happening lately. :p
